# Site settings
name: Manas Gandhi
title: Manas Gandhi | Embedded Engineer
description: Em
url: https://github.com/manaspgandhi
baseurl: ''
email: manaspgandhi@gmail.com
cover: https://bchiang7.github.io/img/og.png
logo: https://bchiang7.github.io/img/emojis/technologist.png
resume: https://bchiang7.github.io/resume.pdf
social:
  - title: email
    url: mailto:manaspgandhi@gmail.com
  - title: twitter
    url: https://twitter.com/ManasGandhi7
  - title: instagram
    url: https://instagram.com/manas.gandhi_
  - title: codepen
    url: http://codepen.io/bchiang7
  - title: github
    url: https://github.com/manaspgandhi
  - title: linkedin
    url: https://www.linkedin.com/in/manas-gandhi/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
